name: test before push
on: # [push, pull_request]
  push:
    branches:
      - '**' # '**' all branches,  master if only one

jobs:
  chechout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Show up tree
        run: tree .
      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test_docker 